annotations:
  tanzuCategory: application
  category: CMS
  licenses: Apache-2.0
  images: |
    - name: apache-exporter
      image: docker.io/bitnami/apache-exporter:1.0.10-debian-12-r4
    - name: os-shell
      image: docker.io/bitnami/os-shell:12-debian-12-r43
    - name: wordpress
      image: docker.io/bitnami/wordpress:6.8.1-debian-12-r0
apiVersion: v2
appVersion: 6.8.1
dependencies:
- condition: memcached.enabled
  name: memcached
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 7.x.x
- condition: mariadb.enabled
  name: mariadb
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 20.x.x
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
name: wordpress
version: 24.2.4
